#!/usr/bin/env node
// Build crawlable static HTML for all public content and navigation pages.
"use strict";
const fs = require("fs");
const vm = require("vm");
const path = require("path");
const crypto = require("crypto");

const ROOT = path.resolve(__dirname, "..");
const SITE_URL = "https://plus-literacy.co.kr";
const SITE_SUFFIX = "고교학점제 탐구보고서 작성 가이드";
const ADSENSE = "ca-pub-8108040193754389";
const appHash = crypto.createHash("sha256").update(fs.readFileSync(path.join(ROOT, "assets/js/app.js"))).digest("hex").slice(0, 10);
const BUILD_VERSION = `20260914-adsense-quality-${appHash}`;

const ctx = { window: { SiteData: {} } };
vm.createContext(ctx);
for (const file of ["site.config.js", "categories.js", "posts.js", "columns.js"]) {
  vm.runInContext(fs.readFileSync(path.join(ROOT, "data", file), "utf8"), ctx, { filename: file });
}
const { config, categories, posts, columns } = ctx.window.SiteData;
const publishedPosts = posts.filter((item) => item.status === "published");
const publishedColumns = columns.filter((item) => item.status === "published");
const categoryBySlug = new Map(categories.map((item) => [item.slug, item]));
const postBySlug = new Map(publishedPosts.map((item) => [item.slug, item]));

function validateSlugs(items, kind) {
  const seen = new Set();
  for (const item of items) {
    if (!/^[a-z0-9-]+$/.test(item.slug || "")) throw new Error(`${kind} has unsafe slug: ${item.slug}`);
    if (seen.has(item.slug)) throw new Error(`${kind} has duplicate slug: ${item.slug}`);
    seen.add(item.slug);
  }
}
validateSlugs(publishedPosts, "post");
validateSlugs(publishedColumns, "column");
validateSlugs(categories, "category");

const esc = (value) => String(value == null ? "" : value)
  .replace(/&/g, "&amp;")
  .replace(/</g, "&lt;")
  .replace(/>/g, "&gt;")
  .replace(/"/g, "&quot;");
const jsonld = (value) => JSON.stringify(value).replace(/</g, "\\u003c");
const cleanDate = (item) => item.updatedAt || item.publishedAt || "";
const sortNewest = (items) => items.slice().sort((a, b) => String(cleanDate(b)).localeCompare(String(cleanDate(a))));

function write(rel, content) {
  const file = path.join(ROOT, rel);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
}

function pruneGenerated(dir, allowed) {
  const full = path.join(ROOT, dir);
  if (!fs.existsSync(full)) return;
  for (const name of fs.readdirSync(full)) {
    if (!name.endsWith(".html") || allowed.has(name)) continue;
    const file = path.join(full, name);
    if (fs.statSync(file).isFile() && fs.readFileSync(file, "utf8").includes("Static HTML generated by tools/build-static.cjs")) fs.unlinkSync(file);
  }
}

function categoriesOf(post) {
  const slugs = Array.isArray(post.categorySlugs) && post.categorySlugs.length ? post.categorySlugs : [post.categorySlug];
  return slugs.map((slug) => categoryBySlug.get(slug)).filter(Boolean);
}

function inCategory(post, slug) {
  return categoriesOf(post).some((category) => category.slug === slug);
}

const indexableCategories = categories.filter((category) => publishedPosts.some((post) => inCategory(post, category.slug)));

function header(prefix) {
  const p = prefix || "";
  return '<a class="skip-link" href="#main-content">본문 바로가기</a>' +
    '<header class="site-header"><div class="container header-inner">' +
    '<a class="brand" href="' + p + 'index.html"><strong>' + esc(config.name) + '</strong></a>' +
    '<nav class="nav" aria-label="주요 메뉴">' +
    '<a href="' + p + 'index.html">홈</a>' +
    '<a href="' + p + 'categories/grade-guide.html">학년별</a>' +
    '<a href="' + p + 'categories/subject-guide.html">과목별</a>' +
    '<a href="' + p + 'categories/track-guide.html">진로·계열별</a>' +
    '<a href="' + p + 'categories/topic-examples.html">주제 예시</a>' +
    '<a href="' + p + 'categories/student-record.html">세특 연결</a>' +
    '<a href="' + p + 'categories/interview.html">면접 대비</a>' +
    '<a href="' + p + 'columns/index.html">칼럼</a>' +
    '<a href="' + p + 'about/index.html">소개</a>' +
    '</nav></div></header>';
}

function footer(prefix) {
  const p = prefix || "";
  return '<section class="footer-cta"><div class="container footer-cta-inner">' +
    '<div class="footer-cta-icon" aria-hidden="true">&#9993;</div><h2>궁금한 점이 있으신가요?</h2>' +
    '<p>탐구보고서, 과목 선택, 세특 연결, 서류기반면접 준비에 대한 의견이나 오류 제보를 보내주세요.</p>' +
    '<a class="button primary" href="' + p + 'contact/index.html">문의하기 →</a></div></section>' +
    '<footer class="site-footer"><div class="container footer-grid">' +
    '<div class="footer-brand"><strong>' + esc(config.name) + '</strong><p>' + esc(config.description) + '</p></div>' +
    '<nav class="footer-column" aria-label="사이트 구조"><h2>사이트</h2>' +
    '<a href="' + p + 'index.html">홈</a><a href="' + p + 'posts/index.html">전체 탐구 글</a>' +
    '<a href="' + p + 'categories/index.html">분류별 탐구 가이드</a><a href="' + p + 'columns/index.html">칼럼</a>' +
    '<a href="' + p + 'about/index.html">소개</a><a href="' + p + 'sitemap/index.html">사이트맵</a></nav>' +
    '<nav class="footer-column" aria-label="정보"><h2>정보</h2>' +
    '<a href="' + p + 'author/index.html">운영자</a><a href="' + p + 'contact/index.html">문의하기</a>' +
    '<a href="' + p + 'privacy/index.html">개인정보처리방침</a><a href="' + p + 'terms/index.html">이용약관</a>' +
    '<a href="' + p + 'disclaimer/index.html">면책고지</a></nav></div>' +
    '<div class="container footer-bottom"><span>© 2026 ' + esc(config.name) + ' · 운영자 ' + esc(config.ownerName) + '</span>' +
    '<a href="mailto:' + esc(config.contactEmail) + '">' + esc(config.contactEmail) + '</a></div></footer>';
}

function documentHtml({ title, description, canonical, prefix = "", body, type = "website", schemas = [], naver = false, page = "", slug = "", scripts = false, ads = true }) {
  const fullTitle = title === SITE_SUFFIX ? title : title + " | " + SITE_SUFFIX;
  return '<!doctype html>\n<html lang="ko">\n<head>\n' +
    (ads ? '<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=' + ADSENSE + '" crossorigin="anonymous"></script>\n' : '') +
    (naver ? '<meta name="naver-site-verification" content="a2a8e01ee3391e4a7bf8fee1fc591c75570d79ee" />\n' : '') +
    '<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n' +
    '<title>' + esc(fullTitle) + '</title>\n<meta name="description" content="' + esc(description) + '">\n' +
    '<link rel="canonical" href="' + canonical + '">\n<meta name="robots" content="index, follow">\n' +
    '<meta property="og:type" content="' + type + '">\n<meta property="og:title" content="' + esc(fullTitle) + '">\n' +
    '<meta property="og:description" content="' + esc(description) + '">\n<meta property="og:url" content="' + canonical + '">\n' +
    '<meta property="og:site_name" content="' + esc(config.name) + '">\n<meta property="og:locale" content="ko_KR">\n' +
    '<meta name="twitter:card" content="summary">\n<link rel="icon" href="' + prefix + 'assets/icons/favicon.svg" type="image/svg+xml">\n' +
    schemas.map((schema) => '<script type="application/ld+json">' + jsonld(schema) + '</script>\n').join("") +
    '<link rel="stylesheet" href="' + prefix + 'assets/css/style.css?v=20260708-4">\n</head>\n' +
    '<body' + (page ? ' data-page="' + esc(page) + '"' : '') + (slug ? ' data-slug="' + esc(slug) + '"' : '') + ' data-prerendered="true"><div id="app">' + header(prefix) + '<main id="main-content" tabindex="-1">' + body + '</main>' + footer(prefix) + '</div>\n' +
    (scripts ? '<script src="' + prefix + 'data/site.config.js?v=20260909-seo"></script>\n<script src="' + prefix + 'data/categories.js?v=20260708-4"></script>\n<script src="' + prefix + 'data/posts.js?v=20260915-student-record-strategy"></script>\n<script src="' + prefix + 'data/columns.js?v=20260714-ai-assessment"></script>\n<script src="' + prefix + 'assets/js/app.js?v=' + BUILD_VERSION + '"></script>\n' : '') +
    '<!-- Static HTML generated by tools/build-static.cjs ' + BUILD_VERSION + ' -->\n</body>\n</html>\n';
}

function postCard(post, prefix = "") {
  const category = categoriesOf(post)[0];
  return '<article class="card"><div class="tag-row"><span class="tag">' + esc(post.grade) + '</span><span class="tag">' + esc(post.subject) + '</span><span class="tag accent">' + esc(post.track) + '</span></div>' +
    '<h3><a href="' + prefix + 'posts/' + esc(post.slug) + '.html">' + esc(post.title) + '</a></h3><p>' + esc(post.summary) + '</p>' +
    '<div class="card-footer"><span>' + esc(category ? category.name : "탐구 글") + '</span><a class="button" href="' + prefix + 'posts/' + esc(post.slug) + '.html">읽기</a></div></article>';
}

function columnCard(column, prefix = "") {
  return '<article class="card"><span class="tag accent">칼럼</span><h3><a href="' + prefix + 'columns/' + esc(column.slug) + '.html">' + esc(column.title) + '</a></h3>' +
    '<p>' + esc(column.summary) + '</p><div class="card-footer"><span>' + esc(cleanDate(column)) + '</span><a class="button" href="' + prefix + 'columns/' + esc(column.slug) + '.html">읽기</a></div></article>';
}

function listBlock(title, items) {
  if (!Array.isArray(items) || !items.length) return "";
  return '<h2>' + esc(title) + '</h2><ul>' + items.map((item) => '<li>' + esc(item) + '</li>').join("") + '</ul>';
}

function postFaq(post) {
  if (Array.isArray(post.faq) && post.faq.length) return post.faq;
  return (post.interviewQuestions || []).slice(0, 2).concat((post.followUpQuestions || []).slice(0, 1)).map((question) => ({
    question,
    answer: "보고서의 교과 개념, 자료 선택 이유, 한계와 보완 방향을 연결해 본인의 말로 설명하는 것이 좋습니다."
  }));
}

function postComparisons(post) {
  if (Array.isArray(post.comparisons) && post.comparisons.length) return post.comparisons;
  const labels = ["주제와 표현", "탐구 과정", "결론과 면접"];
  const common = post.avoidExpressions || [];
  const recommended = post.keyPoints || [];
  return labels.map((label, index) => ({ label, common: common[index] || "근거 없이 넓고 단정적으로 작성", recommended: recommended[index] || "교과 개념과 근거를 바탕으로 구체적으로 작성" }));
}

function renderComparison(items) {
  return '<section class="comparison-section"><h2>흔한 작성 방식과 권장 기준</h2><div class="comparison-table" role="table"><div class="comparison-row comparison-head" role="row"><strong role="columnheader">비교 항목</strong><strong role="columnheader">흔한 방식</strong><strong role="columnheader">권장 기준</strong></div>' + items.map((item) => '<div class="comparison-row" role="row"><strong role="cell">' + esc(item.label) + '</strong><span role="cell">' + esc(item.common) + '</span><span role="cell">' + esc(item.recommended) + '</span></div>').join("") + '</div></section>';
}

function renderPostExtras(post) {
  const faq = postFaq(post);
  const bodyQuestions = Array.isArray(post.bodyQuestions) && post.bodyQuestions.length ? post.bodyQuestions : faq.slice(0, 3);
  const writingSteps = Array.isArray(post.writingSteps) && post.writingSteps.length ? post.writingSteps : (post.reportFlow || []).slice(0, 5).map((title) => ({ title, description: "이 단계에서 선택한 이유, 사용한 근거, 확인한 한계를 구체적으로 기록합니다." }));
  const briefing = Array.isArray(post.briefingPoints) && post.briefingPoints.length ? post.briefingPoints : (post.keyPoints || []).slice(0, 3);
  const mistakes = post.commonMistakes || post.avoidExpressions || [];
  const checklist = post.checklist || post.reportFlow || [];
  const tags = Array.isArray(post.tags) && post.tags.length ? post.tags : [post.grade, post.subject, post.track].filter(Boolean);
  return '<section class="briefing-box"><h2>브리핑 포인트</h2><ul class="list">' + briefing.map((item) => '<li>' + esc(item) + '</li>').join("") + '</ul></section>' +
    renderComparison(postComparisons(post)) +
    '<section class="body-questions"><h2>질문으로 점검하기</h2>' + bodyQuestions.map((item) => '<article><h3>Q. ' + esc(item.question) + '</h3><p>' + esc(item.answer) + '</p></article>').join("") + '</section>' +
    '<section class="writing-steps"><h2>단계별 작성 공식</h2><ol>' + writingSteps.map((item) => '<li><strong>' + esc(item.title) + '</strong><p>' + esc(item.description) + '</p></li>').join("") + '</ol></section>' +
    listBlock("탐구보고서 흐름", post.reportFlow) + listBlock("세특 연결 포인트", post.studentRecordPoints) +
    '<h2>서류기반면접 예상 질문</h2><div class="question-box"><ul>' + (post.interviewQuestions || []).map((item) => '<li>' + esc(item) + '</li>').join("") + '</ul></div>' +
    '<h2>꼬리질문 대비</h2><div class="question-box"><ul>' + (post.followUpQuestions || []).map((item) => '<li>' + esc(item) + '</li>').join("") + '</ul></div>' +
    '<h2>초보자가 자주 하는 실수</h2><ul class="warning-list">' + mistakes.map((item) => '<li><span aria-hidden="true">!</span>' + esc(item) + '</li>').join("") + '</ul>' +
    '<h2>체크리스트</h2><ul class="check-list">' + checklist.map((item) => '<li><span aria-hidden="true">✓</span>' + esc(item) + '</li>').join("") + '</ul>' +
    '<div class="article-tags">' + tags.map((tag) => '<span class="tag">' + esc(tag) + '</span>').join("") + '</div>' +
    '<section class="faq-list"><h2>자주 묻는 질문</h2>' + faq.map((item) => '<details><summary>' + esc(item.question) + '</summary><p>' + esc(item.answer) + '</p></details>').join("") + '</section>';
}

function articleSchema(item, url, type = "Article") {
  return { "@context": "https://schema.org", "@type": type, headline: item.title, description: item.summary || "", datePublished: item.publishedAt, dateModified: cleanDate(item), author: { "@type": "Organization", name: item.authorName || config.ownerName }, publisher: { "@type": "Organization", name: config.name, url: SITE_URL }, mainEntityOfPage: url, url };
}

function breadcrumbSchema(names) {
  return { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: names.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.name, item: item.url })) };
}

function faqSchema(items) {
  return { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: items.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) };
}

function renderPost(post) {
  const canonical = SITE_URL + "/posts/" + post.slug + ".html";
  const related = (post.relatedPostSlugs || []).map((slug) => postBySlug.get(slug)).filter(Boolean);
  const article = '<article class="article-layout"><div class="article-body"><header class="article-header"><div class="tag-row">' +
    [post.grade, post.subject, post.track].filter(Boolean).map((value) => '<span class="tag">' + esc(value) + '</span>').join("") +
    '</div><h1>' + esc(post.title) + '</h1><p class="article-subtitle">' + esc(post.subtitle || post.summary) + '</p>' +
    '<div class="meta byline"><span>' + esc(post.authorName || config.ownerName) + '</span><span>발행 ' + esc(post.publishedAt) + '</span><span>수정 ' + esc(cleanDate(post)) + '</span></div></header>' +
    '<div class="article-top-grid"><section class="article-brief toc-box"><h2>목차</h2><ol class="number-list">' + (post.tableOfContents || []).map((item) => '<li>' + esc(item) + '</li>').join("") + '</ol></section>' +
    '<section class="article-brief summary-box"><h2>핵심 요약</h2><ul class="check-list">' + (post.summaryPoints || post.keyPoints || []).slice(0, 4).map((item) => '<li><span aria-hidden="true">✓</span>' + esc(item) + '</li>').join("") + '</ul></section></div>' +
    (post.content || "") + renderPostExtras(post) +
    (related.length ? '<h2>관련 글</h2><div class="grid two">' + related.map((item) => postCard(item, "../")).join("") + '</div>' : '') +
    '<div class="notice-box"><strong>운영자 안내</strong><p>이 글은 일반 교육 정보이며 특정 대학 합격·학생부 평가·면접 결과를 보장하지 않습니다. 학교와 대학의 공식 안내를 함께 확인해 주세요.</p></div>' +
    '<section class="author-box"><h2>글 작성자</h2><strong>' + esc(post.authorName || config.ownerName) + '</strong><p>' + esc(config.ownerBio) + '</p></section></div>' +
    '<aside class="aside"><div class="panel"><h3>핵심 포인트</h3><ul class="list">' + (post.keyPoints || []).map((item) => '<li>' + esc(item) + '</li>').join("") + '</ul></div>' +
    '<div class="panel"><h3>글 정보</h3><p><a href="../author/index.html">' + esc(config.ownerName || post.authorName) + '</a></p><p>' + esc(config.ownerBio) + '</p></div>' +
    '<div class="panel"><h3>분류</h3><p>' + categoriesOf(post).map((category) => '<a href="../categories/' + esc(category.slug) + '.html">' + esc(category.name) + '</a>').join('<br>') + '</p></div></aside></article>';
  return documentHtml({ title: post.title, description: post.summary, canonical, prefix: "../", body: article, type: "article", schemas: [articleSchema(post, canonical), breadcrumbSchema([{ name: "홈", url: SITE_URL + "/" }, { name: "탐구 글", url: SITE_URL + "/posts/" }, { name: post.title, url: canonical }]), faqSchema(postFaq(post))], page: "post-detail", slug: post.slug, scripts: true });
}

function renderColumn(column) {
  const canonical = SITE_URL + "/columns/" + column.slug + ".html";
  const related = (column.relatedPostSlugs || []).map((slug) => postBySlug.get(slug)).filter(Boolean);
  const body = '<article class="article-layout"><div class="article-body"><header class="article-header column-header"><span class="tag accent">칼럼</span><h1>' + esc(column.title) + '</h1>' +
    '<p class="article-subtitle">' + esc(column.subtitle || column.summary) + '</p><div class="meta byline"><span>' + esc(column.authorName || config.ownerName) + '</span><span>발행 ' + esc(column.publishedAt) + '</span><span>수정 ' + esc(cleanDate(column)) + '</span></div></header>' +
    (column.content || "") + (Array.isArray(column.tags) ? '<div class="article-tags">' + column.tags.map((tag) => '<span class="tag">' + esc(tag) + '</span>').join("") + '</div>' : '') +
    '<div class="notice-box"><strong>칼럼 안내</strong><p>이 칼럼은 운영자의 관점과 일반 교육 정보를 담고 있으며 특정 대학 합격이나 평가 결과를 보장하지 않습니다.</p></div>' +
    '<section class="author-box"><h2>글 작성자</h2><strong>' + esc(column.authorName || config.ownerName) + '</strong><p>' + esc(config.ownerBio) + '</p></section>' +
    (related.length ? '<h2>함께 볼 글</h2><div class="grid two">' + related.map((item) => postCard(item, "../")).join("") + '</div>' : '') +
    '<p class="back-link"><a href="index.html">← 칼럼 목록으로 돌아가기</a></p></div><aside class="aside"><div class="panel"><h3>태그</h3><p>' + esc((column.tags || []).join(", ")) + '</p></div>' +
    '<div class="panel"><h3>안내</h3><p>공식 교육·입시 정보는 학교, 교육청, 대학 입학처 자료를 함께 확인하세요.</p></div></aside></article>';
  return documentHtml({ title: column.title, description: column.summary, canonical, prefix: "../", body, type: "article", schemas: [articleSchema(column, canonical, "BlogPosting"), breadcrumbSchema([{ name: "홈", url: SITE_URL + "/" }, { name: "칼럼", url: SITE_URL + "/columns/" }, { name: column.title, url: canonical }])], page: "column-detail", slug: column.slug, scripts: true });
}

function renderHome() {
  const newest = sortNewest(publishedPosts).slice(0, 9);
  const featured = sortNewest(publishedPosts.filter((item) => item.featured)).slice(0, 6);
  const body = '<section class="hero"><div class="container hero-grid"><div><span class="eyebrow">고교학점제 탐구 설계</span>' +
    '<h1>탐구보고서에서 세특, 서류기반면접까지 한 흐름으로 정리합니다.</h1><p>' + esc(config.description) + '</p>' +
    '<div class="actions"><a class="button primary" href="posts/index.html">탐구 글 보기</a><a class="button" href="categories/index.html">분류별 보기</a></div></div>' +
    '<aside class="hero-panel"><h2>좋은 탐구의 핵심 흐름</h2><ol class="path-list"><li><b>1</b><span>학년과 수업에서 출발해 탐구 질문을 좁힙니다.</span></li><li><b>2</b><span>자료 선택 이유와 분석 기준을 분명히 기록합니다.</span></li><li><b>3</b><span>한계와 후속 질문을 세특·면접 답변으로 연결합니다.</span></li></ol></aside></div></section>' +
    '<section class="section"><div class="container"><h2>이 사이트에서 찾을 수 있는 것</h2><div class="grid"><article class="card"><h3>학년·과목별 작성법</h3><p>고1의 탐색부터 고2의 과목 심화, 고3의 면접 정리까지 학년별 깊이와 교과 개념에 맞춰 설명합니다.</p></article><article class="card"><h3>진로·계열별 탐구 설계</h3><p>인문사회, 상경, 공학, 자연과학, 의생명·보건 계열에서 어떤 질문과 분석 기준을 세울지 안내합니다.</p></article><article class="card"><h3>세특·면접 연결</h3><p>결과만 꾸미지 않고 탐구 동기, 자료 판단, 한계, 후속 질문을 학생의 말로 설명하도록 돕습니다.</p></article></div></div></section>' +
    '<section class="section"><div class="container"><div class="section-header"><div><h2>추천 글</h2><p class="lead">탐구보고서를 처음 설계할 때 먼저 읽어볼 글입니다.</p></div><a class="button" href="posts/index.html">전체 보기</a></div><div class="grid">' + featured.map((item) => postCard(item)).join("") + '</div></div></section>' +
    '<section class="section"><div class="container"><div class="section-header"><div><h2>최신 글</h2><p class="lead">최근 추가하거나 보완한 탐구·면접 가이드입니다.</p></div><a class="button" href="posts/index.html">전체 보기</a></div><div class="grid">' + newest.map((item) => postCard(item)).join("") + '</div></div></section>' +
    '<section class="section"><div class="container"><div class="section-header"><div><h2>탐구보고서 작성 칼럼</h2><p class="lead">탐구 기록을 더 정직하고 설득력 있게 다듬는 관점을 모았습니다.</p></div><a class="button" href="columns/index.html">칼럼 전체 보기</a></div><div class="grid">' + sortNewest(publishedColumns).slice(0, 3).map((item) => columnCard(item)).join("") + '</div></div></section>';
  const websiteSchema = { "@context": "https://schema.org", "@type": "WebSite", name: config.name, url: SITE_URL, description: config.description, inLanguage: "ko-KR" };
  return documentHtml({ title: SITE_SUFFIX, description: config.description, canonical: SITE_URL + "/", body, schemas: [websiteSchema], naver: true, page: "home", scripts: true });
}

function renderPostIndex() {
  const body = '<section class="section"><div class="container"><h1>탐구보고서 작성 가이드 전체 글</h1><p class="lead">학년, 과목, 진로·계열, 세특, 서류기반면접 준비 흐름에 맞춰 작성한 실전 가이드를 모았습니다. 각 글은 주제 선정뿐 아니라 자료 조사, 한계 분석, 기록과 말하기까지 연결합니다.</p><div class="grid">' + sortNewest(publishedPosts).map((item) => postCard(item, "../")).join("") + '</div></div></section>';
  return documentHtml({ title: "탐구보고서 작성 가이드 전체 글", description: "고교학점제 탐구보고서, 세특, 서류기반면접 준비 글 전체 목록입니다.", canonical: SITE_URL + "/posts/", prefix: "../", body, page: "posts", scripts: true });
}

function renderCategoryIndex() {
  const cards = indexableCategories.map((category) => {
    const count = publishedPosts.filter((post) => inCategory(post, category.slug)).length;
    return '<article class="card"><span class="tag">' + esc(category.group) + '</span><h3><a href="' + esc(category.slug) + '.html">' + esc(category.name) + '</a></h3><p>' + esc(category.description) + '</p><div class="card-footer"><span>' + count + '개 글</span><a class="button" href="' + esc(category.slug) + '.html">보기</a></div></article>';
  }).join("");
  const body = '<section class="section"><div class="container"><h1>분류별 탐구보고서 가이드</h1><p class="lead">학년, 과목, 진로·계열, 주제 예시, 세특, 면접 등 지금 필요한 기준을 골라 관련 글을 확인하세요. 같은 글도 내용의 성격에 따라 둘 이상의 분류에서 찾을 수 있습니다.</p><div class="grid">' + cards + '</div></div></section>';
  return documentHtml({ title: "분류별 탐구보고서 가이드", description: "고교학점제 탐구 글을 학년, 과목, 진로·계열, 세특, 면접 기준으로 정리했습니다.", canonical: SITE_URL + "/categories/", prefix: "../", body, page: "categories", scripts: true });
}

function renderCategory(category) {
  const matching = sortNewest(publishedPosts.filter((post) => inCategory(post, category.slug)));
  const body = '<section class="section"><div class="container"><p><a class="button" href="index.html">분류 전체</a></p><h1>' + esc(category.name) + '</h1><p class="lead">' + esc(category.description) + '</p>' +
    '<p>각 글은 탐구 주제만 제시하지 않고 교과 개념, 자료 조사, 한계 분석, 세특 연결, 서류기반면접 질문을 함께 다룹니다. 학생의 실제 수업 경험과 학교 안내에 맞게 조정해 활용하세요.</p><div class="grid">' + matching.map((item) => postCard(item, "../")).join("") + '</div></div></section>';
  return documentHtml({ title: category.name, description: category.description, canonical: SITE_URL + "/categories/" + category.slug + ".html", prefix: "../", body, page: "categories", slug: category.slug, scripts: true });
}

function renderColumnIndex() {
  const body = '<section class="section"><div class="container"><h1>탐구보고서 작성 칼럼</h1><p class="lead">탐구 기록을 더 정직하고 설득력 있게 다듬기 위한 편집팀의 관점과 실전 기준을 모았습니다. 주제의 크기보다 질문의 선명함, 완벽한 결과보다 한계와 보완 과정, 화려한 표현보다 학생이 직접 설명할 수 있는 근거를 중요하게 다룹니다.</p><div class="grid">' + sortNewest(publishedColumns).map((item) => columnCard(item, "../")).join("") + '</div></div></section>';
  return documentHtml({ title: "탐구보고서 작성 칼럼", description: "탐구보고서를 세특과 면접까지 연결하는 교육 정보 칼럼입니다.", canonical: SITE_URL + "/columns/", prefix: "../", body, page: "columns", scripts: true });
}

const trustPages = {
  about: { title: "사이트 소개", description: "탐구보고서 작성 가이드의 목적, 독자, 콘텐츠 작성 기준을 안내합니다.", html: '<h2>이 사이트가 하는 일</h2><p>고교학점제에서는 과목 선택, 수업 활동, 탐구보고서, 세특 기록, 서류기반면접이 따로 움직이지 않습니다. 이 사이트는 학생이 한 번의 탐구를 보고서에서 끝내지 않고 학생부 기록과 면접 답변까지 설명할 수 있도록 흐름을 정리합니다.</p><h2>누구에게 도움이 되나요?</h2><p>탐구 주제를 정하기 막막한 고등학생, 자녀의 과목 선택과 탐구 활동을 이해하려는 학부모, 보고서 내용을 세특과 면접 질문으로 연결하려는 학생을 위해 구성했습니다.</p><h2>콘텐츠 작성 기준</h2><p>특정 대학 합격이나 학생부 평가 결과를 보장하지 않습니다. 학년, 과목, 진로·계열, 탐구 질문, 자료 조사, 한계와 보완, 세특 포인트, 면접 꼬리질문을 현실적인 교육 정보 기준으로 연결합니다.</p><h2>활용 순서</h2><p>학년별 글에서 현재 단계의 깊이를 확인하고, 과목별 글에서 수업 개념과 연결한 질문을 찾으세요. 진로·계열별 글로 방향을 좁힌 뒤 면접 대비 글과 칼럼으로 자신의 탐구를 말로 설명하는 연습을 이어가면 좋습니다.</p>' },
  author: { title: "운영자 소개", description: "탐구가이드 편집팀의 콘텐츠 원칙과 검토 기준을 소개합니다.", html: '<h2>탐구가이드 편집팀</h2><p>탐구가이드 편집팀은 고교학점제 환경에서 학생의 과목 선택, 탐구보고서 작성, 세특 기록, 서류기반면접 준비가 어떻게 연결되는지 학생과 학부모 눈높이로 정리합니다. 좋은 제목을 나열하기보다 학생이 자신의 탐구 과정을 이해하고 직접 설명하도록 구조화된 안내를 만드는 데 초점을 둡니다.</p><h2>전문성의 기준</h2><p>탐구보고서는 학년, 과목, 진로·계열, 수업 개념, 자료 조사 수준에 따라 방향이 달라집니다. 이 요소를 분리하지 않고 주제 선정부터 세특 포인트와 면접 꼬리질문까지 이어지는 흐름으로 검토합니다.</p><h2>콘텐츠 검토 관점</h2><p>합격을 보장하거나 성과를 과장하는 표현, 학생이 실제로 설명하기 어려운 문장을 피합니다. 대신 주제 선택 이유, 탐구 과정, 근거 자료, 한계와 보완점, 후속 질문처럼 학생이 직접 답할 수 있는 요소를 중심으로 안내합니다.</p><h2>운영 철학</h2><p>이 사이트는 보고서를 대신 써주는 곳이 아닙니다. 좋은 탐구는 멋진 제목보다 좋은 질문에서 시작하고, 좋은 기록은 면접에서 자신의 말로 다시 설명할 수 있을 때 힘을 갖는다고 봅니다.</p>' },
  contact: { title: "문의하기", description: "콘텐츠 오류 제보와 교육 정보 관련 의견을 보내는 방법입니다.", html: '<h2>이메일 문의</h2><p>탐구보고서 작성, 과목 선택, 세특 연결, 서류기반면접 준비와 관련한 의견 또는 사이트 오류 제보는 이메일로 보내주세요.</p><div class="contact-email-card"><div><strong>이메일</strong><p><a href="mailto:' + esc(config.contactEmail) + '">' + esc(config.contactEmail) + '</a></p></div></div><h2>문의할 때 알려주시면 좋은 내용</h2><ul><li>오류가 발견된 글 제목과 주소</li><li>확인이 필요한 문장 또는 정보</li><li>참고한 학교·교육청·대학의 공식 안내 주소</li></ul><p>개별 합격 가능성 예측, 대리 작성, 학생부 문장 작성 대행은 제공하지 않습니다. 개인 식별 정보나 민감한 학생 기록은 보내지 마세요.</p>' },
  privacy: { title: "개인정보처리방침", description: "사이트 이용 과정에서 처리될 수 있는 개인정보와 보호 기준을 안내합니다.", html: '<p class="doc-updated">최종 업데이트: 2026-09-14</p><h2>1. 총칙</h2><p>이 사이트는 고교학점제, 탐구보고서, 세특, 서류기반면접 관련 교육 정보를 제공합니다. 본 방침은 사이트 이용 과정에서 처리될 수 있는 개인정보의 기준과 보호 방법을 안내합니다.</p><h2>2. 수집하는 정보</h2><p>회원가입, 댓글, 결제 기능을 제공하지 않으므로 로그인 정보를 수집하지 않습니다. 다만 접속 로그, 브라우저 정보, 방문 일시가 확인될 수 있고 이메일 문의 시 이름, 이메일 주소, 문의 내용이 확인될 수 있습니다.</p><h2>3. 이용 목적과 보관</h2><p>정보는 문의 답변, 오류 확인, 이상 접속 감지, 콘텐츠 품질 개선 및 방문 통계 분석에 사용할 수 있습니다. 문의 정보는 처리 완료 후 6개월 이내 파기를 원칙으로 하며 법령상 의무가 있으면 해당 기간 보관할 수 있습니다.</p><h2>4. 쿠키와 광고</h2><p>Google AdSense를 포함한 광고·분석 서비스가 쿠키를 사용해 광고 제공과 이용 통계를 처리할 수 있습니다. 사용자는 브라우저 설정에서 쿠키를 제한할 수 있으며 Google 광고 설정에서 맞춤 광고를 관리할 수 있습니다.</p><h2>5. 제3자 제공과 이용자 권리</h2><p>법령상 요청이나 명시적 동의가 없는 한 개인정보를 임의로 제3자에게 제공하지 않습니다. 이용자는 자신의 정보에 대한 조회, 수정, 삭제를 이메일로 요청할 수 있습니다.</p><h2>6. 개인정보 보호 문의</h2><p>운영자: ' + esc(config.ownerName) + '<br>이메일: <a href="mailto:' + esc(config.contactEmail) + '">' + esc(config.contactEmail) + '</a></p>' },
  terms: { title: "이용약관", description: "사이트 콘텐츠 이용 조건과 이용자 책임을 안내합니다.", html: '<p class="doc-updated">최종 업데이트: 2026-09-14</p><h2>1. 목적과 제공 서비스</h2><p>본 약관은 사이트의 콘텐츠 이용 조건을 안내합니다. 사이트는 고교학점제 이해, 과목 선택, 탐구보고서 작성, 세특 연결, 서류기반면접 준비에 관한 일반 교육 정보를 제공합니다.</p><h2>2. 콘텐츠 이용</h2><p>글은 개인 학습과 진로 탐색을 위한 참고 자료로 이용할 수 있습니다. 출처 표시 없는 무단 복제, 대량 재배포, 상업적 전재, 자동 수집은 제한됩니다.</p><h2>3. 이용자의 책임</h2><p>학교 교육과정, 교과 담당교사의 안내, 대학 입학처의 공식 자료를 함께 확인해야 합니다. 탐구보고서 작성 시 표절, 허위 작성, 대리 작성은 허용되지 않습니다.</p><h2>4. 금지 행위</h2><p>사이트 운영 방해, 허위 정보 제공, 악성 코드 삽입, 과도한 자동 접근, 타인의 권리 침해 행위를 금지합니다.</p><h2>5. 서비스 변경과 책임 제한</h2><p>정확한 정보 제공을 위해 콘텐츠와 구조를 수정할 수 있습니다. 사이트는 개별 학생의 평가 결과, 대학 합격 여부, 면접 결과를 보장하지 않습니다.</p><h2>6. 문의</h2><p>콘텐츠 이용 문의는 <a href="mailto:' + esc(config.contactEmail) + '">' + esc(config.contactEmail) + '</a>로 보내주세요.</p>' },
  disclaimer: { title: "면책고지", description: "교육 정보의 적용 범위와 공식 자료 확인 원칙을 안내합니다.", html: '<p class="doc-updated">최종 업데이트: 2026-09-14</p><h2>1. 정보 제공 목적</h2><p>콘텐츠는 고등학생과 학부모가 고교학점제, 탐구보고서, 세특, 서류기반면접을 이해하도록 돕기 위한 일반 교육 정보입니다.</p><h2>2. 보장하지 않는 사항</h2><p>특정 대학 합격, 학생부 평가 결과, 면접 점수, 교과 선택의 유불리, 탐구보고서 평가 결과를 보장하지 않습니다.</p><h2>3. 개별 상황의 차이</h2><p>학교별 교육과정 편성, 담당교사의 평가 기준, 학생의 진로 희망, 대학별 전형 방식에 따라 적용 결과가 달라질 수 있습니다.</p><h2>4. 공식 자료 확인</h2><p>입시 제도와 학교 운영 방식은 변경될 수 있습니다. 최종 판단 전 학교 공지, 교육청 자료, 대학 입학처의 최신 공식 안내를 확인해야 합니다.</p><h2>5. 외부 자료와 이용자 판단</h2><p>외부 자료를 언급하더라도 해당 사이트의 정확성과 최신성을 보장하지 않습니다. 실제 보고서 작성과 면접 준비는 학생 본인의 학습 과정과 학교 안내에 맞게 조정해야 합니다.</p>' }
};

function renderTrustPage(key, page) {
  const body = '<section class="section"><div class="container narrow"><h1>' + esc(page.title) + '</h1><p class="lead">' + esc(page.description) + '</p><div class="trust-content">' + page.html + '</div></div></section>';
  return documentHtml({ title: page.title, description: page.description, canonical: SITE_URL + "/" + key + "/", prefix: "../", body, page: key, scripts: key === "contact", ads: false });
}

function renderHtmlSitemap() {
  const categoryLinks = indexableCategories.map((item) => '<li><a href="../categories/' + esc(item.slug) + '.html">' + esc(item.name) + '</a> — ' + esc(item.description) + '</li>').join("");
  const postLinks = sortNewest(publishedPosts).map((item) => '<li><a href="../posts/' + esc(item.slug) + '.html">' + esc(item.title) + '</a></li>').join("");
  const columnLinks = sortNewest(publishedColumns).map((item) => '<li><a href="../columns/' + esc(item.slug) + '.html">' + esc(item.title) + '</a></li>').join("");
  const body = '<section class="section"><div class="container"><h1>사이트맵</h1><p class="lead">탐구보고서 작성 가이드의 모든 주요 페이지를 한곳에서 확인할 수 있습니다.</p><div class="trust-content"><h2>주요 안내</h2><ul><li><a href="../index.html">홈</a></li><li><a href="../about/index.html">사이트 소개</a></li><li><a href="../author/index.html">운영자 소개</a></li><li><a href="../contact/index.html">문의하기</a></li></ul><h2>분류별 가이드</h2><ul>' + categoryLinks + '</ul><h2>탐구 글</h2><ul>' + postLinks + '</ul><h2>칼럼</h2><ul>' + columnLinks + '</ul><h2>운영 정책</h2><ul><li><a href="../privacy/index.html">개인정보처리방침</a></li><li><a href="../terms/index.html">이용약관</a></li><li><a href="../disclaimer/index.html">면책고지</a></li></ul></div></div></section>';
  return documentHtml({ title: "사이트맵", description: "탐구보고서 작성 가이드의 분류, 글, 칼럼, 운영 정책 페이지 목록입니다.", canonical: SITE_URL + "/sitemap/", prefix: "../", body, ads: false });
}

function sitemapXml() {
  const staticUrls = [SITE_URL + "/", SITE_URL + "/categories/", ...indexableCategories.map((item) => SITE_URL + "/categories/" + item.slug + ".html"), SITE_URL + "/posts/", SITE_URL + "/columns/", SITE_URL + "/author/", SITE_URL + "/about/", SITE_URL + "/contact/", SITE_URL + "/privacy/", SITE_URL + "/terms/", SITE_URL + "/disclaimer/", SITE_URL + "/sitemap/"];
  const entries = staticUrls.map((loc) => ({ loc }))
    .concat(publishedPosts.map((item) => ({ loc: SITE_URL + "/posts/" + item.slug + ".html", lastmod: cleanDate(item) })))
    .concat(publishedColumns.map((item) => ({ loc: SITE_URL + "/columns/" + item.slug + ".html", lastmod: cleanDate(item) })));
  return '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + entries.map((entry) => '  <url>\n    <loc>' + esc(entry.loc) + '</loc>' + (entry.lastmod ? '\n    <lastmod>' + esc(entry.lastmod) + '</lastmod>' : '') + '\n  </url>').join("\n") + '\n</urlset>\n';
}

pruneGenerated("posts", new Set(["index.html", "detail.html", ...publishedPosts.map((item) => item.slug + ".html")]));
pruneGenerated("columns", new Set(["index.html", "detail.html", ...publishedColumns.map((item) => item.slug + ".html")]));
pruneGenerated("categories", new Set(["index.html", ...indexableCategories.map((item) => item.slug + ".html")]));

write("index.html", renderHome());
write("posts/index.html", renderPostIndex());
for (const post of publishedPosts) write("posts/" + post.slug + ".html", renderPost(post));
write("categories/index.html", renderCategoryIndex());
for (const category of indexableCategories) write("categories/" + category.slug + ".html", renderCategory(category));
write("columns/index.html", renderColumnIndex());
for (const column of publishedColumns) write("columns/" + column.slug + ".html", renderColumn(column));
for (const [key, page] of Object.entries(trustPages)) write(key + "/index.html", renderTrustPage(key, page));
write("sitemap/index.html", renderHtmlSitemap());
write("sitemap.xml", sitemapXml());
write("ads.txt", "google.com, pub-8108040193754389, DIRECT, f08c47fec0942fa0\n");

console.log("static posts: " + publishedPosts.length);
console.log("static columns: " + publishedColumns.length);
console.log(`static categories: ${indexableCategories.length}`);
console.log("sitemap urls: " + (sitemapXml().match(/<loc>/g) || []).length);
